### ISSUE TITLE
re.compile(feature_regex)

### ISSUE THREAD

**Issue by jlousada315** [mtreinish/ciml#62]
Hello, 

In trainer.py, line 167:
col_regex = re.compile(features_regex)

It seems that features_regex is empty. Added if condition feature_regex is None, set feature_regex = ' '  , an empty string. Now, I have .npz files, but I dont know why I lost in the way. Probably, no labels?

**Comment by kwulffert** [comment]
Hello @johnnylousas,
Thank you for the bug report.
`features_regex` is used to select the columns of the dstat data that you want to use in your dataset. It's a regex, so if you don't specify any, it won't match any column.  
You can specify the `features_regex` for example as follow: 

```
ciml-build-dataset --dataset <dataset-name> --build-name <build-name> --features-regex '(usr|used|1m)'
```
We can set a default value for the regex, so that it won't be mandatory to specify it in the future. In any case, I'd recommend using the filter.

**Comment by jlousada315** [comment]
thank you ! 

I want all the features available and their meaning, where can I find that information ? 

p.s: I can help with the work documentation, I'm interested in the details

**Comment by kwulffert** [comment]
For all features available in the dstat log, you can check https://linux.die.net/man/1/dstat
From our experiments, the most useful ones were (usr|used|1m) (usr|1m) (usr|used) (usr) (used) (1m). They are listed in setup_datasets_tekton.sh
A very cool tool to visualize dstat data: https://github.com/jschaub30/viz_dstat
Help with the documentation would be great :-)!

**Comment by jlousada315** [comment]
Thank you!

Is there a way to convert dstat to .csv? 

Do you prefer this question in another issue ?

**Comment by jlousada315** [comment]
Hello !

I managed to solve the issue above. I think this can be closed now

**Comment by kwulffert** [comment]
@johnnylousas, thank you for updating the readme file. 
I'm glad that you solved the issue you were experiencing.
